### ISSUE TITLE
执行命令后 KotlinNullPointerException 异常

### ISSUE THREAD

**Issue by 37du** [ykisme/LayoutInspector#10]
Exception in thread "main" kotlin.KotlinNullPointerException
	at com.android.layoutinspector.parser.ViewNodeParser.createViewNode(ViewNodeParser.kt:121)
	at com.android.layoutinspector.parser.ViewNodeParser.parseV1ViewNode(ViewNodeParser.kt:92)
	at com.android.layoutinspector.parser.ViewNodeParser.parse(ViewNodeParser.kt:46)
	at com.android.layoutinspector.parser.ViewNodeParser.parse$default(ViewNodeParser.kt:43)
	at com.android.layoutinspector.LayoutInspectorBridge.captureView(LayoutInspectorBridge.kt:44)
	at yk.layout_inspector.Main.main(Main.java:87)

**Comment by 37du** [comment]
一定要指定layoug 中所有View 的id 才行吗
